site_name: LibreGraph
copyright: © 2021 Kopano b.v.
site_author: LibreGraph Maintainers
nav:
    - Home: index.md
    - Discussion: "https://github.com/LibreGraph/libregraph.github.io/discussions"
    - Demo: demo.md

# Project source specific:
repo_name: 'GitHub'
repo_url: 'https://github.com/LibreGraph/libregraph.github.io/discussions'
edit_uri: 'edit/main/docs/'

markdown_extensions:
    - toc:
        separator: "_"
