site_name: LibreGraph
copyright: © 2021 Kopano b.v.
site_author: LibreGraph Maintainers
nav:
  - Home: index.md
  - Development:
    - Architecture: development.md
    - Components: development/components.md
    - Roadmap: development/roadmap.md
  - Discussion: discussion.md
  - Demo: demo.md
  - Links: links.md

# Project source specific:
repo_name: 'GitHub'
repo_url: 'https://github.com/LibreGraph/libregraph.github.io/'
edit_uri: 'edit/main/docs/'
site_url: null

markdown_extensions:
    - toc:
        separator: "_"
        permalink: true

# pip3 install mkdocs-material
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    primary: light blue
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'theme'
